comments updates
oss-aspen/8Knot pull request #249
Opened 2022-12-14 21:31 UTC by cdolfi

Updates on in line comments

2022-12-14 21:55 UTC, JamesKunstle requested changes
one small change, otherwise lgtm

2022-12-14 21:55 UTC, JamesKunstle commented on docs/CONTRIBUTORS.md
>  2. Once the file is created, import the card to the respective page file and put it into the layout
'import the card' could be rewritten as 'import the new visualization file'

2022-12-15 15:41 UTC, cdolfi commented
@JamesKunstle should be good to go. Only failure is on a "spelling" issue from a link

2022-12-15 16:10 UTC, JamesKunstle commented
@cdolfi okay bet. just fix the spelling errors and we'll be good. either fix an actual spelling error ('repective') or add a correctly spelled but unknown word ('oss') to .wordlist.yml in the repo.

2022-12-15 17:41 UTC, cdolfi commented
@JamesKunstle Should be good to go now

2022-12-15 19:18 UTC, JamesKunstle commented
@cdolfi perfect, thank you!

2022-12-15 19:18 UTC, JamesKunstle approved these changes
@cdolfi lgtm

2022-12-15 19:19 UTC, JamesKunstle commented
@cdolfi check rebase error then I'll merge

2022-12-15 20:24 UTC, cdolfi commented
@JamesKunstle on my side its showing no conflicts

2022-12-15 20:52 UTC, JamesKunstle commented
if you're able to merge it via github that's chill but it's telling me "This branch cannot be rebased due to conflicts" above so idk

2022-12-15 20:55 UTC, merged

2022-12-15 20:55 UTC, JamesKunstle commented
huh nice