navbar addition
oss-aspen/8Knot pull request #260
Opened 2023-01-18 23:06 UTC by cdolfi

2023-01-25 17:13 UTC, JamesKunstle approved these changes
@cdolfi is logo2.png a free resource? i.e. can we use it in deployment w/o any copyright?

would also appreciate some more detailed commit messages

2023-01-26 15:59 UTC, JamesKunstle requested changes
couple of things I caught when I pulled your branch

2023-01-26 15:59 UTC, JamesKunstle commented on pages/home/visualizations/issue_metrics.py
> +                    [html.I(className="fa-solid fa-code-commit"), "Commits"],
This should say "Issues"

2023-01-26 15:59 UTC, JamesKunstle commented on pages/home/visualizations/pr_metrics.py
> +                    [html.I(className="fa-solid fa-code-pull-request"), "Pull Request"],
This should say "Pull Requests" plural

2023-01-26 18:05 UTC, cdolfi commented
@JamesKunstle The image is just a place holder, do not have any intentions of actually using it but it is from a tutorial so I think it is fair game. On commit messaging definitely, my plan is to go through on commits and comments once we have a consensus that this is the design direction we want to go in

2023-01-27 18:14 UTC, JamesKunstle commented
@cdolfi If you change the card titles this'll be good to merge. I pushed some more updated changes directly in the urgency of getting a trial to Sean. Can go back and review later when we're trying to merge to dev.

2023-01-27 19:24 UTC, cdolfi commented
@JamesKunstle I am made the changes but Im still getting the error in the logs and the button change not working with the username. Can you check that out on your side?

2023-01-27 19:26 UTC, JamesKunstle commented
@cdolfi yeah will report back

2023-01-27 20:40 UTC, merged