changes to docs to bring up to date
oss-aspen/8Knot pull request #409
Opened 2023-08-16 18:59 UTC by cdolfi

2023-08-23 19:35 UTC, JamesKunstle requested changes
A few wording suggestions and a docker command edit.

2023-08-23 19:35 UTC, JamesKunstle commented on docs/new_viz_guidance.md
> +The [Visualization Template](https://github.com/oss-aspen/8Knot/blob/dev/pages/visualization_template/viz_template.py) can take you step by step on creating your new visualization with boilerplate co
"takes you step-by-step through the process of creating a new visualization." 

The original sentence is a run-on. I think it's sufficient to point to the guide and say "Here's where you learn how to do the thing".

2023-08-23 19:35 UTC, JamesKunstle commented on docs/new_viz_guidance.md
> +1. See if there is some minor changes or additional columns that could be added to
"Exhaust the possibility of making minor changes, such adding new columns or aggregations, to existing queries."

2023-08-23 19:35 UTC, JamesKunstle commented on docs/new_viz_guidance.md
> +Note: make sure to do a "docker system prune -af" before rebuilding to be able to access any new or edited queries.
Using 'docker compose down' is sufficient. 'docker system prune -af' will destroy EVERYTHING they're running, including any other docker services or volumes.

2023-08-25 19:48 UTC, JamesKunstle approved these changes
Looks perfect

2023-08-25 19:49 UTC, JamesKunstle commented
@cdolfi Could you please run the spell checker once more locally? Then it's good to merge.

2023-08-25 19:53 UTC, cdolfi commented
@JamesKunstle How do I go about doing it? From what I can see in my local check the spell check is not in there

2023-08-25 21:18 UTC, JamesKunstle commented
> @JamesKunstle How do I go about doing it? From what I can see in my local check the spell check is not in there

Ah yeah, I see, that's a Github action. Just correct the misspelling that's noted in the action.

2023-08-28 15:24 UTC, merged