Add issues closed line graph and update hovertemplate
oss-aspen/8Knot pull request #479
Opened 2023-09-28 18:16 UTC by christinaexyou

@cdolfi Resolves part of https://github.com/oss-aspen/8Knot/issues/468 and https://github.com/oss-aspen/8Knot/issues/470 by making the following changes:

* Adds line for issues closed
* Updates the hover template with Date, indicating the time window for which prolificacy is calculated

2023-09-29 17:10 UTC, cdolfi requested changes
Lets add issue comments to this one too and rebase to main and will be good to go!

2023-09-29 18:48 UTC, christinaexyou commented
@cdolfi Changes made:
* Added issue comment line
* Updated legend labels to be more concise - changed `PR Review Comment` to `PR Comment` and `PR Request Review` to `PR Review`

2023-10-02 18:27 UTC, cdolfi requested changes
Seems to be something weird happening format wise. Once that is fixed overall in the file I think it will be ready to merge (hard to see with current state, check out the "review" view if you want a good look)

2023-10-02 18:27 UTC, cdolfi commented on 8Knot/pages/contributors/visualizations/contrib_importance_over_time.py
> +PAGE = "contributors"
remove spaces

2023-10-02 18:27 UTC, cdolfi commented on 8Knot/pages/contributors/visualizations/contrib_importance_over_time.py
> +                                            id=f"threshold-{PAGE}-{VIZ_ID}",
change back format

2023-10-02 18:27 UTC, cdolfi commented on 8Knot/pages/contributors/visualizations/contrib_importance_over_time.py
> +                            [   dbc.Label(
same on format

2023-10-02 20:24 UTC, cdolfi commented
@christinaexyou let me know when this is ready for re-review. If there is not an obvious way of fixing file wide this @JamesKunstle might have some guidance

2023-10-02 20:41 UTC, JamesKunstle commented
@cdolfi @christinaexyou I'll pull this now and take a look to see if I have any ideas.

2023-10-02 21:01 UTC, JamesKunstle commented
Working on this, though I'm getting a DBReadFailure for some reason, so I may need to spend some time debugging tomorrow before I can actually review this PR.

2023-10-04 18:02 UTC, JamesKunstle commented
@christinaexyou 

## Review 

I pulled your most updated branch and tried the following orgs/repos, but neither 'Issues Closed' nor 'Issue Messages' lines appeared. 

'chaoss' org
'3scale' org
'kubernetes/kubernetes' repo

This is a screenshot of what I get for 'kubernetes/kubernetes':
<img width="749" alt="Screenshot 2023-10-04 at 1 58 47 PM" src="https://github.com/oss-aspen/8Knot/assets/52969093/66c32bb5-dc81-4dc5-a155-b2c155187372">

And this is my current branch's log:
<img width="668" alt="Screenshot 2023-10-04 at 2 01 02 PM" src="https://github.com/oss-aspen/8Knot/assets/52969093/57243fc4-804b-4be8-b7c6-ccfabd7a7f33">

Which I believe is up to date.


## One additional request

I'd love it if the Action Type was in the hover information. That'd make reading the graph much easier.

2023-10-05 12:54 UTC, christinaexyou commented
@cdolfi @JamesKunstle Changes made:
* Reverted formatting
* `Issue Closed` and `Issue Comment` line graphs are visible
* Shortened `PR Request ...` labels to `PR`
* Updated hover template to display action type

2023-10-05 14:42 UTC, cdolfi approved these changes
lgtm! Once james reviews we can merge

2023-10-06 22:31 UTC, JamesKunstle commented
@christinaexyou Yuh this looks great, gonna merge it.

2023-10-06 22:31 UTC, merged