Update packages
oss-aspen/8Knot pull request #631
Opened 2024-01-26 20:23 UTC by JamesKunstle

had to make small pandas API changes since we're updating like 6 versions.

2024-01-30 18:09 UTC, JamesKunstle commented
I've unpinned all the versions to catch everything up, but I'm going to repin them after this PR. I'm going to try to use pipenv but if that still sucks I'll check out Poetry

2024-01-31 21:42 UTC, cdolfi requested changes
Small changes and needs to be brought up to date. Once that is done and an issue is created for repinning itll be good to merge!

2024-01-31 21:42 UTC, cdolfi commented on 8Knot/pages/contributions/visualizations/cntrb_pr_assignment.py
> +        # .rename(columns={"assignee": "count", "index": "assignee"})
Should this comment still be there?

2024-01-31 21:42 UTC, cdolfi commented on 8Knot/pages/contributions/visualizations/cntrib_issue_assignment.py
> +        # .rename(columns={"assignee": "count", "index": "assignee"})
same as above

2024-02-06 19:17 UTC, JamesKunstle commented on 8Knot/pages/chaoss/visualizations/contrib_importance_pie.py
> +    # df = df.append({"cntrb_id": "Other", action_type: t_sum - df_sum}, ignore_index=True)
removed

2024-02-06 19:18 UTC, JamesKunstle commented on 8Knot/pages/contributors/visualizations/contrib_importance_pie.py
> +    # df = df.append({"cntrb_id": "Other", action_type: t_sum - df_sum}, ignore_index=True)
removed

2024-02-06 19:23 UTC, JamesKunstle commented
@cdolfi 
1) re-pinned dependencies using modern Python app dependency management best-practice
2) removed comments you notes
3) I think the commits I made are discrete changes and shouldn't be squashed.

2024-02-06 19:46 UTC, cdolfi commented
@JamesKunstle Sweet, can you bring the branch back up to date and ill merge! Not too sure how it got out of date but since it is package stuff i want to make sure we are thorough

2024-02-07 20:13 UTC, JamesKunstle commented
@cdolfi should be up to date

2024-02-13 17:56 UTC, JamesKunstle commented
@cali squashed commits, rebased onto current dev,  should be good to go

2024-02-13 19:09 UTC, cdolfi approved these changes
lgtm and ran on fresh build

2024-02-13 19:09 UTC, merged